name: "paramstore"
version: "1.0.0"
usage: "Inject values from AWS SSM Parameter Store into Helm values file"
description: "Inject values from AWS SSM Parameter Store into Helm values file"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/helm-paramstore"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
